### ISSUE TITLE
inXcode7 and ios9 appCrash

### ISSUE THREAD

**Issue by NagiYan** [kconner/KMCGeigerCounter#11]
this is how i use:   

    _window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    [[[UIApplication sharedApplication] delegate] setWindow:_window];
    
    // main view controller
    homeViewController = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateInitialViewController];
    [homeViewController setDelegate:self];

    UINavigationController* navView = [[DirectionUINavigationController alloc] initWithRootViewController:homeViewController];
    
    [_window setRootViewController:navView];
    [_window makeKeyAndVisible];

    #ifndef APP_STORE_RELEASE
        [KMCGeigerCounter sharedGeigerCounter].enabled = YES;
    #endif

error info:
*** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3505.16/UIApplication.m:3294

remove  KMCGeigerCounter app ok.

**Comment by kconner** [comment]
I've prepared a few changes toward supporting iOS 9, but the SKView technique I'm using has bad side effects that I haven't solved. I can still detect when CPU activity delays the application event loop, but I can no longer detect when long drawing times cause frames to skip out of process. Until I figure that out, crashing completely is better than giving false readings.

For the moment, the geiger counter will only work in iOS 7 and 8. Sorry about this!

**Comment by champo** [comment]
@kconner this is really hard to figure when migrating from Xcode 6 to 7. I've just spent quite a bit a of time figuring it out. Disabling the feature and logging an error seems way more reasonable to me.

**Comment by sauchye** [comment]
Run Xcode 7 Crash
```
KMCGeigerCounter[19143:610019]

 *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], 

/BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3505.16/UIApplication.m:3294
```

**Comment by cxw** [comment]
why can the skview force the cadisplaylink to match the drawing time

**Comment by kconner** [comment]
Please see #15 for more information about this.
