### ISSUE TITLE
Xcode 7 ios9

### ISSUE THREAD

**Issue by mrchenhao** [kconner/KMCGeigerCounter#13]
KMCGeigerCounter[59404:2861474] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'

**Comment by lsqiang** [comment]
'KMCGeigerCounter.m' modify this method!

- (void)setEnabled:(BOOL)enabled
{
    if (_enabled != enabled) {
        if (enabled) {
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
               [self enable];
            });
        } else {
            [self disable];
        }

        _enabled = enabled;
    }
}

**Comment by jeyben** [comment]
This worked. Will you add it to the sourcecode?

**Comment by kconner** [comment]
I have a simpler fix for this bug that involves giving the meter window a root view controller. That's available in the `ios9` branch. But it's not ready to ship as a new version of the pod because of another serious bug; see #15 for details.
