### ISSUE TITLE
iOS 9+: SKView presence for measurement affects performance of regular views

### ISSUE THREAD

**Issue by kconner** [kconner/KMCGeigerCounter#15]
I've fixed some bugs in the `iOS 9` branch:
- Overlay window needed a root view controller
- Example application didn't create its table views properly
- The meter window would be hidden if the status bar was hidden

Thanks for writing in about those. But I'm not able to ship a new release of the pod yet, because I haven't solved the most serious problem, which has to do with my method of measuring the timing of drawing.

```
    // Low framerates can be caused by CPU activity on the main thread or by long compositing time in (I suppose)
    // the graphics driver. If compositing time is the problem, and it doesn't require a lot of main thread activity
    // between frames, then the framerate can drop without CADisplayLink detecting it.
    // Therefore, put an empty 1pt x 1pt SKView in the window. It shouldn't interfere with the framerate, but
    // should cause the CADisplayLink callbacks to match the timing of drawing.
    // TODO: This should be lightweight but affects the framerate on iOS 9, particularly in the example application.
    // Maybe if I use only the SKView and not the CADisplayLink?
    // No, that doesn't help. The SKView alone is causing the drawing latency. The CADisplayLink does not interfere.
    // SceneKit doens't exist before iOS 8, so I'd prefer not to rely on it.
    // A GLKViewController works on the default run loop, so it doesn't get updates during core animation scrolling.
    // Using a custom view with -drawRect: or -displayLayer:, callbacks happen just as often as CADisplayLink.
    // I need a new way to accurately detect when a frame is drawn to the screen without affecting the framerate.
```

I've tried several things, but I don't have a solution yet. If you want to see where I am on this, check out the `ios9` branch. To see the problem for yourself, try running the example application on your device with and without this line in `-[KMCGeigerCounter start]`:

```
    [[UIApplication sharedApplication].keyWindow addSubview:self.sceneView];
```

You'll notice that without the line, the framerate on scrolling the first tab is not smooth, but the meter reads 60. This is because the cost of rendering that view is not on the main thread like layout. With that line included, I'm able to detect the delays, but the framerate actually gets worse and should not.

**Comment by kconner** [comment]
Just to go over it again, because it is a pretty gross hack and I'm not sure if it even worked because of the reason I thought it worked: CADisplayLink calls are usually 60 times a second, but fewer can happen if too much CPU activity, like layout, causes the run loop to slow down. That's one kind of dropped frame. The other kind of dropped frame is when the CPU activity for the frame finishes in time, but then the prepared layers take so long to draw that the screen isn't updated in time for the hardware refresh. CADisplayLink will get a call during that time, but that doesn't mean OpenGL/Metal has finished drawing. So I'm using an SKView, which has to be updated by a main thread run loop every frame, to inject another per-frame event before the CADisplayLink call. Only when the scene is ready will the display link callback fire, and the scene can't be updated until it's been drawn. That has the practical upshot of making CADisplayLink calls actually match the displayed frames more closely. Or so goes the theory. On iOS 9, the SKView seems to be so expensive that it makes application performance worse, meaning the measurements are incorrect.

**Comment by cbowns** [comment]
(coming here via a friend)

Weird idea, but: perhaps this is the time for private API usage? I would very nearly guarantee that there's a private API somewhere in Core Animation which would notify you about the frame drawing rate.

(My thinking: I don't use KMCGeigerCounter (yet), but if/when I do, it strikes me as a debug-only tool, and I'd definitely not include it in release builds.)

**Comment by kconner** [comment]
Excellent point. I think you're right.

**Comment by kconner** [comment]
rdar://26907286

**Comment by kconner** [comment]
We're now on iOS 12 beta and our device power has come a long way. Frame drops seem to come mostly come from Auto Layout these days, not blended layers. I'm now comfortable with explicitly not measuring GPU frame drops. This issue is a won't-fix.
