### ISSUE TITLE
iOS 9.3.X: Crash because window has no UIViewController

### ISSUE THREAD

**Issue by FGoessler** [kconner/KMCGeigerCounter#20]
Using this pod on a device with iOS 9.3.2 I get a crash because UIKit complains that every window needs to have a rootViewController set after ```application:didFinishLaunchingWithOptions:```.

This happens because the KMCGeigerCounter creates its own window but doesn't set a rootViewController there. So the fix is to just set some UIViewController on it:

```[self.window setRootViewController:[UIViewController new]];```

Would be nice if you could please make this small change and push out a new release to CocoaPods. 😉

**Comment by FGoessler** [comment]
Oh I just saw that you have an iOS 9 branch with the fix on it. Will use it from that branch then for now!

**Comment by kconner** [comment]
Note that #15 shows the iOS 9 branch is still flawed. You may not get the
best measurements. Keep using the Core Animation instrument alongside this
tool.
