### ISSUE TITLE
sample project cannot run 

### ISSUE THREAD

**Issue by zgpeace** [kconner/KMCGeigerCounter#21]
2017-08-26 18:35:17.370 KMCGeigerCounter[71863:6870637] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.7.47/UIApplication.m:3677
2017-08-26 18:35:17.432 KMCGeigerCounter[71863:6870637] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a365b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001098c2141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a369cf2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010945c536 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x000000010b2f6c46 -[UIApplication _runWithMainScene:transitionContext:completion:] + 3343
	5   UIKit                               0x000000010b2f37f3 -[UIApplication workspaceDidEndTransaction:] + 182
	6   FrontBoardServices                  0x000000010e3bd5f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	7   FrontBoardServices                  0x000000010e3bd46d -[FBSSerialQueue _performNext] + 186
	8   FrontBoardServices                  0x000000010e3bd7f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	9   CoreFoundation                      0x000000010a30bc01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	10  CoreFoundation                      0x000000010a2f10cf __CFRunLoopDoSources0 + 527
	11  CoreFoundation                      0x000000010a2f05ff __CFRunLoopRun + 911
	12  CoreFoundation                      0x000000010a2f0016 CFRunLoopRunSpecific + 406
	13  UIKit                               0x000000010b2f208f -[UIApplication _run] + 468
	14  UIKit                               0x000000010b2f8134 UIApplicationMain + 159
	15  KMCGeigerCounter                    0x00000001092e47af main + 111
	16  libdyld.dylib                       0x000000010dd3e65d start + 1
	17  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by kconner** [comment]
Please see #15.
