### ISSUE TITLE
Instance variables must have a constant size

### ISSUE THREAD

**Issue by iliaskarim** [kconner/KMCGeigerCounter#3]
When compiling with the iOS 8.1SDK in a Swift & Objective-C++ project, I get the build error above on line 18 of KMCGeigerCounter.m

Apparently static NSInteger const is not "good enough" for array sizes? http://stackoverflow.com/questions/3988122/static-const-int-not-good-enough-for-array-size

Anyone else encounter this issue? How did you work around it, besides just using #define or hardcoding the value 60?

**Comment by mikeabdullah** [comment]
I'm seeing this issue too, in an Objective-C (no Swift) project, trying to compile in the files directly.

**Comment by iliaskarim** [comment]
@answer-huang here is a simple fix: https://github.com/djz-code/KMCGeigerCounter/commit/a088233603b48c05cf71928d7121485803b8d14f

@kconner I've added the files to my project directly (not using CocoaPods)

I wonder whether the issue has to do with llvm C/C++ dialect settings, but I haven't found a setting that fixes the build. Personally I think it's a good idea to #define the constant for compatibility; I would hate to see other developers deterred from using this useful project because of a compilation issue :)

**Comment by iliaskarim** [comment]
Ah, I took a look at the example project's build settings and found the difference. `C Language Dialect` must be set to `GNU99` or `gnu11`. My Xcode seems to default to `C99` instead. I still recommend using #define

**Comment by kconner** [comment]
`#define` it is. Thanks for your help.
