### ISSUE TITLE
Floating point conversion errors

### ISSUE THREAD

**Issue by iosdevben** [kconner/KMCGeigerCounter#8]
When you have Warnings set to be treated as Errors in Xcode the following prevent the app from building:

KMCGeigerCounter.m:198:74: Implicit conversion loses floating-point precision: 'double' to 'CGFloat' (aka 'float')

KMCGeigerCounter.m:237:47: Implicit conversion loses floating-point precision: 'double' to 'UIWindowLevel' (aka 'float')

**Comment by kconner** [comment]
Sorry, I don't reproduce this, at least not in the sample project. Do you want to make a pull request that corrects the problem with explicit casts?
